# Generated by Django 6.0.6 on 2026-06-24 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ModelMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
                ("roc_auc", models.FloatField()),
                ("train_samples", models.PositiveIntegerField()),
                ("test_samples", models.PositiveIntegerField()),
                ("confusion_matrix", models.JSONField(default=list)),
                ("classification_report", models.TextField()),
                ("trained_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Model metrics",
                "ordering": ["-trained_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("amount_inr", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "payment_channel",
                    models.CharField(
                        choices=[
                            ("UPI", "UPI"),
                            ("IMPS", "IMPS"),
                            ("NEFT", "NEFT"),
                            ("RTGS", "RTGS"),
                            ("CARD", "Card"),
                            ("WALLET", "Wallet"),
                        ],
                        default="UPI",
                        max_length=10,
                    ),
                ),
                ("device_type", models.CharField(default="ANDROID", max_length=10)),
                ("payer_state", models.CharField(max_length=64)),
                ("beneficiary_state", models.CharField(max_length=64)),
                ("merchant_category", models.CharField(default="P2P", max_length=32)),
                ("merchant_risk_score", models.FloatField(default=0.2)),
                ("account_age_days", models.PositiveIntegerField(default=365)),
                ("beneficiary_age_days", models.PositiveIntegerField(default=30)),
                ("txn_velocity_1h", models.PositiveSmallIntegerField(default=1)),
                ("distance_km", models.FloatField(default=5.0)),
                ("hour_of_day", models.PositiveSmallIntegerField(default=12)),
                ("day_of_week", models.PositiveSmallIntegerField(default=2)),
                ("new_beneficiary", models.BooleanField(default=False)),
                ("high_velocity", models.BooleanField(default=False)),
                ("odd_hour", models.BooleanField(default=False)),
                ("geo_mismatch", models.BooleanField(default=False)),
                ("vpn_detected", models.BooleanField(default=False)),
                ("first_large_txn", models.BooleanField(default=False)),
                ("fraud_probability", models.FloatField(blank=True, null=True)),
                (
                    "risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("MINIMAL", "Minimal"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=12,
                    ),
                ),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "ground_truth_fraud",
                    models.BooleanField(
                        blank=True, help_text="Known label for evaluation", null=True
                    ),
                ),
                ("risk_factors", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FraudAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                (
                    "recommended_action",
                    models.CharField(default="REVIEW", max_length=64),
                ),
                ("resolved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert",
                        to="fraud_detection.transaction",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
