# Generated by Django 6.0.6 on 2026-06-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PolicyChallenge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=64)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "india_context",
                    models.TextField(
                        help_text="Why this matters specifically for India"
                    ),
                ),
                ("mitigation", models.TextField(blank=True)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                        ],
                        default="MEDIUM",
                        max_length=16,
                    ),
                ),
            ],
            options={
                "ordering": ["category", "title"],
            },
        ),
        migrations.CreateModel(
            name="PolicyFramework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "authority",
                    models.CharField(help_text="e.g. RBI, MeitY, NPCI", max_length=64),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("summary", models.TextField()),
                ("relevance_to_ai", models.TextField()),
                ("source_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-year", "name"],
            },
        ),
    ]
